---
- hosts: vms
  gather_facts: no
  roles:
    - role: prepare_os
      become: true
    - role: chroot_jail
      become: true

- hosts: jailed_rpis
  gather_facts: no
  roles:
  - role: usb_autorunner
    become: true
